### ISSUE TITLE
c++ 和 python 结果差别很大 

### ISSUE THREAD

**Issue by SheenChi** [pengzhendong/silero-vad#11]
东哥，你那边有没有对比过c++和python的运行结果，我这面使用项目里面的测试语音 test_16k.wav 不进行降噪处理,使用非流式模式，发现两者差别很大，不确定是不是我这面哪里配置错误导致的，结果如下：
python: 
[{'segment': 0, 'start': 1.66, 'end': 3.044}, {'segment': 1, 'start': 4.476, 'end': 6.628}, {'segment': 2, 'start': 9.372, 'end': 11.62}, {'segment': 3, 'start': 12.156, 'end': 14.82}]
[1.666, 3.044]
[4.476, 6.628]
[9.372, 11.62]
[12.156, 14.82]

c++：
[1.666, 2.974]
[5.634, 5.822]
[9.474, 9.694]
[10.178, 10.43]
[10.626, 11.198]
[12.354, 14.75]

**Comment by pengzhendong** [comment]
一些后处理的参数可能没对齐

**Comment by SheenChi** [comment]
好的，多谢，对比了一下主要区别在于c++没有将context送入推理，另外min_sil_dur_ms 和 speech_pad_ms也有一些区别，目前结果基本一致了
