### ISSUE TITLE
这个模型可以微调吗？

### ISSUE THREAD

**Issue by coreeey** [pengzhendong/silero-vad#6]
噪声较大的情况下，这个模型假阳性有点多，现在有微调这个模型的项目不？

**Comment by pengzhendong** [comment]
> 噪声较大的情况下，这个模型假阳性有点多，现在有微调这个模型的项目不？

没有，我在代码里添加了谐波能量的分析，可以尝试打开：https://github.com/pengzhendong/silero-vad/blob/b9d1357ee2ce5e079f16b31051a5cbf48a18cd29/silero_vad/silero_vad.py#L329

**Comment by coreeey** [comment]
好的，谢谢大佬
