### ISSUE TITLE
Plan to support Silero VAD 5.0?

### ISSUE THREAD

**Issue by GoArsenal** [pengzhendong/silero-vad#7]
[Silero VAD 5.0](https://github.com/snakers4/silero-vad/releases/tag/v5.0) is released, any plan to support it?

**Comment by pengzhendong** [comment]
> [Silero VAD 5.0](https://github.com/snakers4/silero-vad/releases/tag/v5.0) is released, any plan to support it?

@GoArsenal Thanks for your attention. Done.

https://github.com/pengzhendong/silero-vad/commit/e26af177ed379e1cb9931e6f0299ea0f89206c6a
